---
title: "Visualisation Project"
author: "Rashid Elhawli"
date: "3 June 2019"
output: html_notebook
runtime: shiny
---

```{r message=FALSE}
library(shiny)
library(dplyr)
library(networkD3)
library(tidyr)
```

```{r}
# read in the data for countries we're interested in
au <- read.csv("aus_challenges.csv") #australia
ca <- read.csv("ca_challenges.csv") #canada
us <- read.csv("us_challenges.csv") #us
uk <- read.csv("uk_challenges.csv") #uk
```

```{r}
# narrowing down df to relevant data for viz
au_challenges <- select(au, c(2, 8, 12))
ca_challenges <- select(ca, c(2, 8, 12))
us_challenges <- select(us, c(2, 8, 12))
uk_challenges <- select(uk, c(2, 8, 12))
```

```{r}
colnames(au_challenges) <- c("Country", "Row.item.label", "Value")
colnames(ca_challenges) <- c("Country", "Row.item.label", "Value")
colnames(us_challenges) <- c("Country", "Row.item.label", "Value")
colnames(uk_challenges) <- c("Country", "Row.item.label", "Value")
```

```{r}
# replacing 'NA' for 0
au_challenges$Value[is.na(au_challenges$Value)] <- 0
ca_challenges$Value[is.na(ca_challenges$Value)] <- 0
us_challenges$Value[is.na(us_challenges$Value)] <- 0
uk_challenges$Value[is.na(uk_challenges$Value)] <- 0
```

```{r}
# combining the data frames together
semi_merge <- rbind.data.frame(au_challenges, ca_challenges)
semi_merge <- rbind.data.frame(semi_merge, us_challenges)
results <- rbind.data.frame(semi_merge, uk_challenges)
```

```{r}
# group dataframe by country and challenge
# preps dataframe for sankey diagram format
chal <- results %>%
  group_by(Country, Row.item.label) %>%
  summarise(Value = sum(Value))
```

```{r}
# create all nations nodes df
country <- unique(as.character(chal$Country))
challenges <- unique(as.character(chal$Row.item.label))
nodes <- data.frame(node = c(0:17),
                  name = c(country, challenges))
```

```{r}
# australian nodes df
country_au <- unique(as.character(au_challenges$Country))
challenges_au <- unique(as.character(au_challenges$Row.item.label))
nodes_au <- data.frame(node = c(0:14),
                  name = c(country_au, challenges_au))
```

```{r message=FALSE}
# australian links df
aus_chal <- au_challenges %>%
  left_join(nodes_au, by = c("Country" = "name")) %>%
  rename(ctry_id = node) %>%
  left_join(nodes_au, by = c("Row.item.label" = "name")) %>%
  rename(chng_id = node)
```

```{r}
# australian sankey
sankey_challengeau <- sankeyNetwork(Links = aus_chal, Nodes = nodes_au, Source = "ctry_id", Target = "chng_id", Value = "Value", NodeID = "name", fontSize = 14, nodeWidth = 30)
```

```{r}
# us nodes df
country_us <- unique(as.character(us_challenges$Country))
challenges_us <- unique(as.character(us_challenges$Row.item.label))
nodes_us <- data.frame(node = c(0:14),
                  name = c(country_us, challenges_us))
```

```{r message=FALSE}
# us links df
us_chal <- us_challenges %>%
  left_join(nodes_us, by = c("Country" = "name")) %>%
  rename(ctry_id = node) %>%
  left_join(nodes_us, by = c("Row.item.label" = "name")) %>%
  rename(chng_id = node)
```

```{r}
# us sankey
sankey_challengeus <- sankeyNetwork(Links = us_chal, Nodes = nodes_us, Source = "ctry_id", Target = "chng_id", Value = "Value", NodeID = "name", fontSize = 14, nodeWidth = 30)
```

```{r}
# canadian nodes df
country_ca <- unique(as.character(ca_challenges$Country))
challenges_ca <- unique(as.character(ca_challenges$Row.item.label))
nodes_ca <- data.frame(node = c(0:14),
                  name = c(country_ca, challenges_ca))
```

```{r message=FALSE}
# canadian links df
ca_chal <- ca_challenges %>%
  left_join(nodes_ca, by = c("Country" = "name")) %>%
  rename(ctry_id = node) %>%
  left_join(nodes_ca, by = c("Row.item.label" = "name")) %>%
  rename(chng_id = node)
```

```{r}
# canadian sankey
sankey_challengeca <- sankeyNetwork(Links = ca_chal, Nodes = nodes_ca, Source = "ctry_id", Target = "chng_id", Value = "Value", NodeID = "name", fontSize = 14, nodeWidth = 30)
```

```{r}
# uk nodes df
country_uk <- unique(as.character(uk_challenges$Country))
challenges_uk <- unique(as.character(uk_challenges$Row.item.label))
nodes_uk <- data.frame(node = c(0:14),
                  name = c(country_uk, challenges_uk))
```

```{r message=FALSE}
# uk links df
uk_chal <- uk_challenges %>%
  left_join(nodes_uk, by = c("Country" = "name")) %>%
  rename(ctry_id = node) %>%
  left_join(nodes_uk, by = c("Row.item.label" = "name")) %>%
  rename(chng_id = node)
```

```{r}
# uk sankey
sankey_challengeuk <- sankeyNetwork(Links = uk_chal, Nodes = nodes_uk, Source = "ctry_id", Target = "chng_id", Value = "Value", NodeID = "name", fontSize = 14, nodeWidth = 30)
```

```{r message=FALSE}
# create overall links df
chal1 <- chal %>%
  left_join(nodes, by = c("Country" = "name")) %>%
  rename(ctry_id = node) %>%
  left_join(nodes, by = c("Row.item.label" = "name")) %>%
  rename(chng_id = node)
```

```{r}
# draw sankey diagram
sankey_challenge <- sankeyNetwork(Links = chal1, Nodes = nodes, Source = "ctry_id", Target = "chng_id", Value = "Value", NodeID = "name", fontSize = 14, nodeWidth = 30)
```

```{r, echo=FALSE}
# make sankey diagram a web app using Shiny

  ui <- fluidPage(
    
    # Application title
    titlePanel("SME Challenges in Australia, Canada, US and UK"),
    
    inputPanel(
      selectInput("country", "Country",c("AU", "CA", "US", "UK", "All Nations"))
    ),
    
    #dimensions of the sankey in the browser
    sankeyNetworkOutput("plot", width ="1000px", height = "650px"))
  
  server <- function(input, output, session) {
    #rendering sankey to the server
    output$plot = renderSankeyNetwork({
      if (input$country == "AU") {
        print(sankey_challengeau)
      } else if (input$country == "CA") {
        print(sankey_challengeca)
      } else if (input$country == "US") {
        print(sankey_challengeus)
      } else if (input$country == "UK") {
        print(sankey_challengeuk)
      } else if (input$country == "All Nations") {
        print(sankey_challenge)
      }
        
    })
  }
shinyApp(ui, server)
```
